### ISSUE TITLE
Connection to farcaster account from local debugger is giving an error

### ISSUE THREAD

**Issue by spennyp** [wevm/frog-archived#128]
### Describe the bug

Used to be able to connect my Farcaster, but now I am unable to.
Warpcast side looks working, but getting an error on frame server

### Steps To Reproduce

1. Hit connect farcaster in top right of local debugger
2. Scan with phone
3. Confirm and pay $2 to connect from warpcast
4. Wait for broadcast, says success from warpcast side\
5. See error on console, and local debugger just stays with QR code up

![Screenshot 2024-03-09 at 15 21 32](https://github.com/wevm/frog/assets/31705429/7b378827-2d8d-4cea-804b-eb6adef86ecd)

### Frog Version

0.5.5

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by dalechyn** [comment]
Hey, @spennyp, I haven't met this issue myself, but from reading the related business logic there is something that I need to note:
- Frog generates random key pair on every login requests, therefore if you've logged in for the first time, you will have to pay for the second login, **unless** you're passing `appFid` and `appMnemonic` to the `Frog` constructor instance.

Have you passed those options or not?

Aside from that, the specific error that you've encountered is weird because the `response.messages` for your fid is indeed iterable.
https://api.hub.wevm.dev/v1/userDataByFid?fid=18655

**Comment by dalechyn** [comment]
> * Frog generates random key pair on every login requests, therefore if you've logged in for the first time, you will have to pay for the second login, **unless** you're passing `appFid` and `appMnemonic` to the `Frog` constructor instance.

@jxom, maybe we could persist the generated key-pair in the localstorage or somewhere so we don't pay multiple times for sign-ins?

**Comment by tmm** [comment]
It's stored in a cookie already.

https://github.com/wevm/frog/blob/main/src/dev/routes.tsx#L398-L400
