### ISSUE TITLE
The FrameContext.res({ {image, ... }) function incorrectly sanitizes "image" URL inputs as HTML

### ISSUE THREAD

**Issue by bstchow** [wevm/frog-archived#243]
### Describe the bug

The FrameContext.res({ {image, ... }) function param incorrectly sanitizes "image" URL inputs as HTML.

e.g. If you pass in a URL with an image URL with  &-separated query params, the &'s will be replaced with "&amp;" as would be expected for HTML input.

### Steps To Reproduce

`FrameContext.res({ image: "example.com?hello=world&foo=bar" })` results in an image url exposed by the Frog debugger as 
"example.com?hello=world&amp;foo=bar"

### Frog Version

latest

### TypeScript Version

n/a

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

### Anything else?

I saw some sanitized ampersands in [this issue](https://github.com/wevm/frog/issues/157) as well, not sure if related

**Comment by dalechyn** [comment]
![Screenshot 2024-04-11 at 13 02 41](https://github.com/wevm/frog/assets/35642018/061f9cff-f480-4397-aed3-7c8cc6acbafd)
![Screenshot 2024-04-11 at 13 02 52](https://github.com/wevm/frog/assets/35642018/13f37903-812c-4d43-bcd9-6f8d8a436be6)

```ts
export const app = new Frog({
  ui: { vars },
}).frame('/', (c) => {
  return c.res({
    image: 'https://picsum.photos/id/870/200/300?grayscale&blur=2',
  })
})
```

Can't reproduce. Make sure to add `https://` protocol prefix to the URL as otherwise it might be treated wrongly.
Reopen if the issue isn't fixed.
