### ISSUE TITLE
devtools don't work in next template with edge runtime enabled

### ISSUE THREAD

**Issue by dalechyn** [wevm/frog-archived#274]
### Describe the bug

`serveStatic` imported from `frog/serve-static` becomes `undefined` when runtime is set to edge.

### Link to Minimal Reproducible Example

https://github.com/heyJonBray/frog-minimal/tree/error

### Frog Version

0.8.5

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

### Anything else?

https://discord.com/channels/1156791276818157609/1231006852637130845/1231203587720478805

**Comment by tmm** [comment]
> `serveStatic` imported from `frog/serve-static` becomes `undefined` when runtime is set to edge.

This is intentional as edge runtimes don't support `fs` and other modules used by `serveStatic`. Instead, you should copy the devtools static assets — either via `vercel build` or a [custom script](https://github.com/wevm/frog/blob/main/templates/cloudflare-worker/package.json#L9) — and use `devtools` [`assetsPath`](https://frog.fm/dev/devtools#assetspath).
