### ISSUE TITLE
Failed in Warpcast Validator but looks ok in frog local dev

### ISSUE THREAD

**Issue by louislucrypto** [wevm/frog-archived#350]
### Describe the bug

[134.209.36.149:3000/dev](http://134.209.36.149:3000/dev) Frog looks good but 
However warpcast validator give me errors of "**_validateFrameEmbed 400 - Frame image error: Invalid ContentType: 'text/plain; charset=UTF-8'._**"
[warpcast.com/~/developers...](https://warpcast.com/~/developers/frames?url=http%3A%2F%2F134.209.36.149%3A3000%2F)

### Link to Minimal Reproducible Example

https://warpcast.com/~/developers/frames?url=http%3A%2F%2F134.209.36.149%3A3000%2F

### Steps To Reproduce

i have attached link
compare 
- https://warpcast.com/~/developers/frames?url=http%3A%2F%2F134.209.36.149%3A3000%2F
- http://134.209.36.149:3000/dev

### Frog Version

0.11.5

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

### Anything else?

Feel free to reach out to me on warpcast 
[@loui](https://warpcast.com/loui)

**Comment by louislucrypto** [comment]
Ideally I think Frog local dev environment should give me same error so I could fix it.

**Comment by nestorbonilla** [comment]
I'm also running into the `validateFrameEmbed 400 - Missing image URL` error. Has anyone found a solution or workaround for this?

**Comment by louislucrypto** [comment]
@nestorbonilla looks like this is not only me. What version is your frog? 
I'm thinking maybe this is introduced in some latest update.

**Comment by nestorbonilla** [comment]
@louislucrypto this error is with version `0.11.5`. I just upgraded to version `0.11.6`, and with any additional modification I'm having a new one, but similar: `validateFrameEmbed 400 - Frame image error: Invalid ContentType: ''.`

**Comment by dalechyn** [comment]
Hey @louislucrypto.

> Link to Minimal Reproducible Example
https://warpcast.com/~/developers/frames?url=http%3A%2F%2F134.209.36.149%3A3000%2F
Steps To Reproduce
i have attached link
compare
https://warpcast.com/~/developers/frames?url=http%3A%2F%2F134.209.36.149%3A3000%2F
http://134.209.36.149:3000/dev

Thanks for attaching those, but I'd appreciate a separate repo with an actual min. reproduction, as I cannot really debug the issue without running it locally and can only assume what might be wrong.

Your frame fails in Warpcast Validator because indeed the `Content-type` isn't `image/png` but `text/html`.

That shouldn't be the case normally unless you're overriding this header yourself. Frog is using `hono-og`/`resvg`+`yoga` that set this header by default to `image/png`.

I can only **assume** you're running a reverse proxy like NGINX, it might mess up those headers.

Anyway, I can only assist effectively if you will provide a minimal reproducible example.
Please re-open the issue if you add one.

**Comment by benbaessler** [comment]
> Hey @louislucrypto.
> 
> > Link to Minimal Reproducible Example
> > https://warpcast.com/~/developers/frames?url=http%3A%2F%2F134.209.36.149%3A3000%2F
> > Steps To Reproduce
> > i have attached link
> > compare
> > https://warpcast.com/~/developers/frames?url=http%3A%2F%2F134.209.36.149%3A3000%2F
> > http://134.209.36.149:3000/dev
> 
> Thanks for attaching those, but I'd appreciate a separate repo with an actual min. reproduction, as I cannot really debug the issue without running it locally and can only assume what might be wrong.
> 
> Your frame fails in Warpcast Validator because indeed the `Content-type` isn't `image/png` but `text/html`.
> 
> That shouldn't be the case normally unless you're overriding this header yourself. Frog is using `hono-og`/`resvg`+`yoga` that set this header by default to `image/png`.
> 
> I can only **assume** you're running a reverse proxy like NGINX, it might mess up those headers.
> 
> Anyway, I can only assist effectively if you will provide a minimal reproducible example. Please re-open the issue if you add one.

I'm facing the same issue, not using NGINX or anything else. Locally, the frame renders but when testing it in the Warpcast frame validator it throws this error:  `Frame image error: Invalid ContentType: 'text/html'.`

It even displays the content type to be `image/png` in the UI.

![Screenshot from 2024-06-13 02-43-42](https://github.com/wevm/frog/assets/78696428/ca1589d0-058c-4b56-8516-40a73f296ad7)

**Comment by oleksandrtarapata** [comment]
same problem

repo for reproduction https://github.com/limitless-labs-group/limitless-trade-frame

test dev link http://localhost:3000/markets/0xAEfCa6eC53A3EED5e46d87C55e4c57B77aEe49Ba

test deployed link for a frame https://limitless-trade-frame.vercel.app/markets/0xAEfCa6eC53A3EED5e46d87C55e4c57B77aEe49Ba
